# Generated by Django 3.2.4 on 2021-06-18 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('recipeID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Instruction', models.TextField()),
                ('Img', models.ImageField(upload_to='imagesdb/')),
                ('Date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
