# Generated by Django 3.2.4 on 2021-06-19 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_recipe_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='Img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
