# Generated by Django 3.2.4 on 2021-06-19 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_recipe_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='Date',
            new_name='CreateDate',
        ),
    ]
