# Generated by Django 3.2.4 on 2021-06-19 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_date_recipe_createdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeUser',
            fields=[
                ('recipeID', models.AutoField(primary_key=True, serialize=False)),
                ('userid', models.CharField(max_length=100)),
            ],
        ),
    ]
