# Generated by Django 3.2.4 on 2021-06-19 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_recipeuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeuser',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.recipe'),
        ),
    ]
