# Generated by Django 3.2.4 on 2021-06-19 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20210619_1947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='CategoryID',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='CountryID',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='IngredientsID',
        ),
    ]
