# Generated by Django 3.2.4 on 2021-06-19 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20210619_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='CategoryID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='CountryID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.country'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='IngredientsID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.indredients'),
            preserve_default=False,
        ),
    ]
