# Generated by Django 3.2.4 on 2021-06-19 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20210619_2000'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Indredients',
            new_name='Ingredients',
        ),
    ]
