# Generated by Django 3.2.4 on 2021-06-19 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_rename_indredients_ingredients'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredients',
            options={'verbose_name': 'Ингредиент', 'verbose_name_plural': 'Ингредиенты'},
        ),
    ]
