# Generated by Django 3.2.4 on 2021-06-20 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20210620_1847'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='CategoryID',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='IngredientsID',
        ),
    ]
