# Generated by Django 3.2.4 on 2021-06-20 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20210620_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredientsrecipe',
            name='CountsOnRecipe',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
