# Generated by Django 2.2.10 on 2021-06-21 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_remove_ingredientsrecipe_countsonrecipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredientsrecipe',
            name='CountsOnRecipe',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
