# Generated by Django 2.2.10 on 2021-06-21 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_ingredientsrecipe_countsonrecipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='CreateDate',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='Img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='Instruction',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recommendation',
            name='Name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='RecommendationUser',
        ),
    ]
