# Generated by Django 2.2.10 on 2021-06-23 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_auto_20210623_0510'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredients',
            name='IDtype',
        ),
        migrations.AlterField(
            model_name='typeingredient',
            name='IDtype',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
