# Generated by Django 2.2.10 on 2021-06-23 03:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_auto_20210623_0635'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredients',
            name='IDtype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.TypeIngredient'),
        ),
    ]
