# Generated by Django 2.2.10 on 2021-06-23 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_ingredients_idtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dictionary',
            fields=[
                ('DictionaryID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Description', models.TextField()),
            ],
            options={
                'verbose_name': 'Определение',
                'verbose_name_plural': 'Определения',
            },
        ),
    ]
