# Generated by Django 3.2.4 on 2021-06-23 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_dictionary'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentTips',
            fields=[
                ('EquipmentTipsID', models.AutoField(primary_key=True, serialize=False)),
                ('EquipmentTipsName', models.CharField(max_length=100)),
                ('EquipmentTipsDescriptions', models.TextField()),
                ('EquipmentTipsImg', models.ImageField(blank=True, null=True, upload_to='')),
            ],
            options={
                'verbose_name': 'Советы по оборудованию',
                'verbose_name_plural': 'Совет по оборудованию',
            },
        ),
        migrations.AlterField(
            model_name='rating',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='recipeuser',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
