# Generated by Django 2.2.10 on 2021-06-23 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_equipmenttips'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipmenttips',
            options={'verbose_name': 'Правило', 'verbose_name_plural': 'Правила'},
        ),
    ]
