# Generated by Django 2.2.10 on 2021-06-28 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
